---
- hosts: control_node_1
  become: yes

  tasks:
    - name: check for updates
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/dpkg/lock"

    - name: Install OpenJDK dependencies
      apt:
        name:
          - ca-certificates
          - apt-transport-https
          - dirmngr
          - gnupg
          - software-properties-common
        state: present
    - name: Add OpenJDK APT key
      apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
        state: present
    - name: Add OpenJDK repository
      apt_repository:
        repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bullseye main
        state: present
    - name: check for updates
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install OpenJDK
      apt:
        name: adoptopenjdk-11-hotspot
        state: present

    - name: Download Jenkins Debian package
      get_url:
        url: https://pkg.jenkins.io/debian-stable/binary/jenkins_2.361.1_all.deb
        dest: /tmp/jenkins.deb

    - name: Install Jenkins dependencies
      apt:
        name:
          - default-jre
          - procps
        state: present

    - name: Install Jenkins package
      apt:
        deb: /tmp/jenkins.deb
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: true
